version: 0.2

phases:
  pre_build:
    commands:
      - dotnet restore Schedule.Api/Schedule.Api.csproj
  build:
    commands:
      - dotnet build Schedule.Api/Schedule.Api.csproj
  post_build:
    commands:
      - dotnet publish -c Release -r linux-x64 --self-contained false Schedule.Api
artifacts:
  files:
    - '**/*'
  base-directory: ./Schedule.Api/bin/Release/netcoreapp3.1/linux-x64/publish/